### ISSUE TITLE
Issue with gstreamer plugin

### ISSUE THREAD

**Issue by davoz96** [natumbri/mopidy-youtube#58]
Hello,
when i try to stream youtube links i get this error:

`WARNING  Could not find a text/html decoder to handle media.
WARNING  GStreamer warning: gst-stream-error-quark: No decoder available for type 'text/html'. (6)
ERROR    GStreamer error: gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12)`

Shouldn't gstreamer plugins already be installed from mopidy's apt?
I run debian jessie and mopidy 2.0 on my machine

**Comment by sirhopcount** [comment]
I have the same problem even though I installed the gstreamer0.10-plugins-bad package. Also running Raspbian jessie (lite) and mopdiy 2.0.

These are packages that are installed when installing 'gstreamer0.10-plugins-bad' on jessie:

```
The following NEW packages will be installed:
  freepats gstreamer0.10-plugins-bad gstreamer0.10-plugins-base libass5 libcdaudio1 libcroco3 libdc1394-22 libdca0
  libdirac-encoder0 libdirectfb-1.2-9 libenca0 libfaad2 libfftw3-double3 libflite1 libfribidi0 libgme0 libgsm1
  libgstreamer-plugins-bad0.10-0 libgstreamer-plugins-base0.10-0 libgstreamer0.10-0 libjpeg8 libkate1 libltdl7
  libmhash2 libmimic0 libmms0 libmodplug1 libmpcdec6 libofa0 libopenal-data libopenal1 libraptor2-0 librasqal3
  librdf0 librsvg2-2 librsvg2-common libschroedinger-1.0-0 libslv2-9 libsoundtouch0 libspandsp2 libvo-aacenc0
  libvo-amrwbenc0 libwildmidi-config libwildmidi1 libxslt1.1 libxvidcore4 libyajl2 libzbar0 libzvbi-common libzvbi0
```

**Comment by kingosticks** [comment]
Mopidy **v2.0** uses gstreamer**1.0** packages, not gtsreamer**0.10**.

**Comment by sirhopcount** [comment]
Yeah just found that out and it works fine now. Got confused because the README says to use gstreamer0.10-plugins-bad. 

Anyway, my issues have been fixed, hope it also works for @davoz96

**Comment by kingosticks** [comment]
Good spot, I've updated it in https://github.com/mopidy/mopidy-youtube/commit/d79bd5524a42210bc7acc9bf88275c9df62c73f7

If @davoz96 can confirm the solution we can close this.

**Comment by camilonova** [comment]
@kingosticks I just installed the package according to d79bd55 but I still get the same error.

Any ideas?

**Comment by camilonova** [comment]
After a lot of testing the issue is related to https://github.com/mopidy/mopidy/issues/1526

This issue can be closed.

**Comment by Rambomst** [comment]
I have the same issue however I don't think it is related to mopidy/mopidy#1526. I have tried setting the timeout and nothing changes.

These are the GStreamer related packages installed

> root@raspberrypi1:~# dpkg --list | grep GStreamer
> ii  gir1.2-gst-plugins-base-1.0           1.4.4-2                                   armhf        Description: GObject introspection data for the GStreamer Plugins Base library
> ii  gir1.2-gstreamer-1.0                  1.4.4-2                                   armhf        Description: GObject introspection data for the GStreamer library
> ii  gstreamer0.10-alsa:armhf              0.10.36-2                                 armhf        GStreamer plugin for ALSA
> ii  gstreamer1.0-alsa:armhf               1.4.4-2                                   armhf        GStreamer plugin for ALSA
> ii  gstreamer1.0-libav:armhf              1.4.4-2                                   armhf        libav plugin for GStreamer
> ii  gstreamer1.0-omx                      1.0.0.1-0+rpi18rpi1g                      armhf        GStreamer OpenMAX plugins
> ii  gstreamer1.0-plugins-bad:armhf        1.4.4-2.1rpi4rpi1g                        armhf        GStreamer plugins from the "bad" set
> ii  gstreamer1.0-plugins-base:armhf       1.4.4-2                                   armhf        GStreamer plugins from the "base" set
> ii  gstreamer1.0-plugins-good:armhf       1.4.4-2                                   armhf        GStreamer plugins from the "good" set
> ii  gstreamer1.0-plugins-ugly:armhf       1.4.4-2                                   armhf        GStreamer plugins from the "ugly" set
> ii  gstreamer1.0-pulseaudio:armhf         1.4.4-2                                   armhf        GStreamer plugin for PulseAudio
> ii  gstreamer1.0-tools                    1.4.4-2                                   armhf        Tools for use with GStreamer
> ii  gstreamer1.0-x:armhf                  1.4.4-2                                   armhf        GStreamer plugins for X11 and Pango
> rc  libgstreamer-plugins-bad0.10-0:armhf  0.10.23-7.4                               armhf        GStreamer development files for libraries from the "bad" set
> ii  libgstreamer-plugins-bad1.0-0:armhf   1.4.4-2.1rpi4rpi1g                        armhf        GStreamer development files for libraries from the "bad" set
> ii  libgstreamer-plugins-base0.10-0:armhf 0.10.36-2                                 armhf        GStreamer libraries from the "base" set
> ii  libgstreamer-plugins-base1.0-0:armhf  1.4.4-2                                   armhf        GStreamer libraries from the "base" set
> ii  libgstreamer0.10-0:armhf              0.10.36-1.5                               armhf        Core GStreamer libraries and elements
> ii  libgstreamer1.0-0:armhf               1.4.4-2                                   armhf        Core GStreamer libraries and elements
> ii  python-gst-1.0                        1.2.1-1.1                                 armhf        GStreamer GObject Introspection overrides for Python

Could the issue be caused by "gstreamer0.10-alsa" still being installed? We use LXDE to run chromium in kiosk mode and it appears LXDE requires "gstreamer0.10-alsa"
